### ISSUE TITLE
Error accessing energy

### ISSUE THREAD

**Issue by couteiral** [openmm/openmm-torch#31] opened 2021-04-14 14:55 UTC
Hi OpenMM team,

First of all, many thanks for your fantastic work on the OpenMM suite of projects!

I have been trying to get OpenMM-Torch to work on a couple of test systems, but I seem to be struggling with a particular error whenever I try to access the energy, be it directly via ``context.getState(getEnergy=True)``, or even with the Reporter objects when I use the higher-level API. The error in particular is:

```
Traceback (most recent call last):
  File "/homes/rubiera/Downloads/FoldSet/bug.py", line 46, in <module>
    print(context.getState(getEnergy=True).getPotentialEnergy())
  File "/data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/simtk/openmm/openmm.py", line 4888, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
simtk.openmm.OpenMMException: The autograd engine was called while holding the GIL. If you are using the C++ API, the autograd engine is an expensive operation that does not require the GIL to be held so you should release it with 'pybind11::gil_scoped_release no_gil;'. If you are not using the C++ API, please report a bug to the pytorch team.
Exception raised from execute at /tmp/pip-req-build-2handpz9/torch/csrc/autograd/python_engine.cpp:111 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6a (0x7f02d3b24dba in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd8 (0x7f02d3b21338 in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x122 (0x7f0317ef6452 in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x2e900f2 (0x7f03144a60f2 in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<bool>, bool, std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0x6a (0x7f03144a6afa in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x3497f56 (0x7f0314aadf56 in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #6: at::Tensor::_backward(c10::ArrayRef<at::Tensor>, c10::optional<at::Tensor> const&, c10::optional<bool>, bool) const + 0x1c9 (0x7f0312b6adb9 in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #7: TorchPlugin::ReferenceCalcTorchForceKernel::execute(OpenMM::ContextImpl&, bool, bool) + 0x7cd (0x7f029527d85d in /data/gull/rubiera/anaconda3/envs/ani/lib/plugins/libOpenMMTorchReference.so)
frame #8: OpenMM::ContextImpl::calcForcesAndEnergy(bool, bool, int) + 0xca (0x7f0295a0fc8a in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/simtk/openmm/../../../../libOpenMM.so.7.5)
frame #9: OpenMM::Context::getState(int, bool, int) const + 0x15a (0x7f0295a0e78a in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/simtk/openmm/../../../../libOpenMM.so.7.5)
frame #10: <unknown function> + 0x169148 (0x7f0295e2c148 in /data/gull/rubiera/anaconda3/envs/ani/lib/python3.9/site-packages/simtk/openmm/_openmm.cpython-39-x86_64-linux-gnu.so)
<omitting python frames>
frame #27: __libc_start_main + 0xf2 (0x7f034d1ec082 in /lib64/libc.so.6)
```

The code to reproduce this, under OpenMM 7.5 with OpenMM-Torch 1.0, both installed fom conda-forge, is:

```python
import torch
import numpy as np
from sys import stdout
from simtk.unit import *
from simtk.openmm import *
from simtk.openmm.app import *
from openmmtorch import TorchForce


class ForceModule(torch.nn.Module):
    """A central harmonic potential as a static compute graph"""
    def forward(self, positions):
        """The forward method returns the energy computed from positions.

        Parameters
        ----------
        positions : torch.Tensor with shape (nparticles,3)
           positions[i,k] is the position (in nanometers) of spatial dimension k of particle i

        Returns
        -------
        potential : torch.Scalar
           The potential energy (in kJ/mol)
        """
        return torch.sum(positions**2)

# Create system
system = System()
for _ in range(500):
    system.addParticle(1.)
positions = Quantity(np.random.uniform(high=100, size=[500, 3]), angstrom)

# Set up force
module = torch.jit.script(ForceModule())
module.save('model.pt')
torch_force = TorchForce('model.pt')
system.addForce(torch_force)

# Run dynamics
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.001*picosecond)
context = Context(system, integrator)
context.setPositions(positions)
LocalEnergyMinimizer.minimize(context)
for _ in range(100):
    integrator.step(50)
    print(context.getState(getEnergy=True).getPotentialEnergy())
```

At first glance, the traceback suggests that the error is coming from the Torch library, rather than from the OpenMM bindings. Is there a solution to this problem? Is there a more idiomatic way to access the energy, without conflicting with Torch?

Best wishes,

**Comment by peastman** [comment] 2021-04-14 16:22
This was caused by a change in behavior of PyTorch.  To fix it we had to make a change (https://github.com/openmm/openmm/pull/3061) to OpenMM.  That change will be in 7.5.1.  We're hoping to get out a release candidate today or tomorrow.

**Comment by raimis** [comment] 2021-09-30 12:49
I tried this with:
- OpenMM 7.6.0
- OpenMM-Torch 0.4
- PyTorch 1.8.0

And it works:
```
$ python debug.py 
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
0.3110635280609131 kJ/mol
2.3475184440612793 kJ/mol
7.614446640014648 kJ/mol
17.188777923583984 kJ/mol
31.933258056640625 kJ/mol
52.41033935546875 kJ/mol
78.81639099121094 kJ/mol
112.2433090209961 kJ/mol
151.9664306640625 kJ/mol
196.81875610351562 kJ/mol
246.92709350585938 kJ/mol
303.01812744140625 kJ/mol
363.44976806640625 kJ/mol
427.2153015136719 kJ/mol
493.13067626953125 kJ/mol
561.5486450195312 kJ/mol
633.1156616210938 kJ/mol
707.966552734375 kJ/mol
785.586181640625 kJ/mol
864.2783203125 kJ/mol
943.887451171875 kJ/mol
1022.3966064453125 kJ/mol
1096.98974609375 kJ/mol
1167.2860107421875 kJ/mol
1232.6671142578125 kJ/mol
1295.996337890625 kJ/mol
1358.203125 kJ/mol
1418.62744140625 kJ/mol
1474.6671142578125 kJ/mol
1524.7752685546875 kJ/mol
1568.58984375 kJ/mol
1606.562744140625 kJ/mol
1639.5355224609375 kJ/mol
1668.6422119140625 kJ/mol
1692.9322509765625 kJ/mol
1711.5062255859375 kJ/mol
1728.66748046875 kJ/mol
1740.7742919921875 kJ/mol
1749.06201171875 kJ/mol
1754.8798828125 kJ/mol
1760.42431640625 kJ/mol
1764.431396484375 kJ/mol
1768.381591796875 kJ/mol
1769.466552734375 kJ/mol
1773.573974609375 kJ/mol
1777.8232421875 kJ/mol
1781.355712890625 kJ/mol
1782.084716796875 kJ/mol
1783.966064453125 kJ/mol
1785.39111328125 kJ/mol
1786.1534423828125 kJ/mol
1785.8095703125 kJ/mol
1782.858642578125 kJ/mol
1779.21875 kJ/mol
1774.3094482421875 kJ/mol
1771.784912109375 kJ/mol
1771.5914306640625 kJ/mol
1771.561767578125 kJ/mol
1773.0604248046875 kJ/mol
1776.565673828125 kJ/mol
1781.80322265625 kJ/mol
1788.160888671875 kJ/mol
1793.3846435546875 kJ/mol
1797.6722412109375 kJ/mol
1800.9085693359375 kJ/mol
1802.108154296875 kJ/mol
1800.1728515625 kJ/mol
1797.2108154296875 kJ/mol
1793.998046875 kJ/mol
1791.045654296875 kJ/mol
1790.651611328125 kJ/mol
1787.59814453125 kJ/mol
1782.72412109375 kJ/mol
1777.253662109375 kJ/mol
1772.0048828125 kJ/mol
1767.814208984375 kJ/mol
1764.366943359375 kJ/mol
1762.39208984375 kJ/mol
1759.589111328125 kJ/mol
1753.6717529296875 kJ/mol
1748.3140869140625 kJ/mol
1741.85791015625 kJ/mol
1734.042236328125 kJ/mol
1727.980712890625 kJ/mol
1723.8427734375 kJ/mol
1720.8115234375 kJ/mol
1719.3863525390625 kJ/mol
1718.53466796875 kJ/mol
1718.02294921875 kJ/mol
1717.30859375 kJ/mol
1716.105712890625 kJ/mol
1713.011962890625 kJ/mol
1710.554443359375 kJ/mol
1709.700439453125 kJ/mol
1711.0821533203125 kJ/mol
1710.6234130859375 kJ/mol
1708.805908203125 kJ/mol
1704.0 kJ/mol
1698.1611328125 kJ/mol
1691.1751708984375 kJ/mol
```
@couteiral could you verify that works for you too and we can close this.

**Comment by raimis** [comment] 2021-12-13 17:39
This has already been fixed!

**Closed by raimis** 2021-12-13 17:39 UTC
